### 
GET http://localhost:3000/

### List
GET http://localhost:3000/api/v1/todos

### Create
POST http://localhost:3000/api/v1/todos
Content-Type: application/json

{
	"text": "test"
}

### Create Error
POST http://localhost:3000/api/v1/todos
Content-Type: application/json

{
	"teXt": "test"
}

### Rename
PATCH http://localhost:3000/api/v1/todos/100/rename
Content-Type: application/json

{
	"text": "test"
}